config/routes.rb
Rails.application.routes.draw do

  root 'blogs#index'
 

    resources :blogs

end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

def index
	@blogs = Blog.all
end

def new
@blog = Blog.new
end

def create
	@blog = Blog.new(blog_params)
	if @blog.save
		redirect_to blogs_path
	else

	end
end

def show
	@blog = Blog.find(params[:id])
end

def destroy
	blog = Blog.find(params[:id])
	blog.destroy
	redirect_to blogs_path
end

def edit
@blog = Blog.find(params[:id])
end

def update
	@blog = Blog.find(params[:id])
	if @blog.update_attributes(blog_params)
		redirect_to blogs_path
	else

	end
end

 private

  def blog_params
    params.require(:blog).permit(:title, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/edit.html.erb
<%= form_for @blog do |f| %>
Title: <%= f.text_field :title %><br/>
Descritpion: <%= f.text_area :description %>
<%= f.submit "update" %>
<% end %>

app/views/blogs/index.html.erb
<%= link_to "New Blog Post", new_blog_path %><br/>

<% if @blogs.empty? %>
"No records"
<% else %>
Title:
<% @blogs.each do |blog| %>
<%= link_to blog.title, blog_path(blog.id) %>
<%= link_to "edit", edit_blog_path(blog.id) %>
<%= button_to "delete", blog_path(blog.id), :method=>:delete, :class=>:destroy %>
<br/>
<% end %>
<% end %>

git 

app/views/blogs/new.html.erb
<%= form_for @blog do |f| %>
Title: <%= f.text_field :title %><br/>
Descritpion: <%= f.text_area :description %>
<%= f.submit "create" %>
<% end %>

app/views/blogs/show.html.erb
<%= @blog.title %>
<%= @blog.description %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirstTestProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>